# Generated by Django 5.1.7 on 2025-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_urun_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='kategori_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urun_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urun_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urun_name',
            field=models.CharField(max_length=200),
        ),
    ]
